const images = [
    "New_Name",
    "Banded_Demoiselle_(C.png",
    "Beautiful_Demoiselle.png",
    "Broad-bodied_Chaser_.png",
    "Buff-tailed_Bumblebe.png",
    "Cave_Spider_(Meta_me.png",
    "Comma_butterfly_(Pol.png",
    "Common_Blue_butterfl.png",
    "Common_Crab_Spider_(.png",
    "Common_Darter_dragon.png",
    "Common_Fox_Spider_(A.png",
    "Common_Frog_(Rana_te.png",
    "Common_Lizard_(Zooto.png",
    "Common_Toad_(Bufo_bu.png",
    "Death_Cap_mushroom_(.png",
    "Devil’s_Coach_Horse_.png",
    "European_Adder_(Vipe.png",
    "European_Garden_Spid.png",
    "False_Black_Widow_Sp.png",
    "Fen_Raft_Spider_(Dol.png",
    "Fly_Agaric_mushroom_.png",
    "Grass_Snake_(Natrix_.png",
    "Great_Crested_Newt_(.png",
    "Hammock-web_Spider_(.png",
    "Harlequin_Ladybird_(.png",
    "Holly_Blue_butterfly.png",
    "Jelly_Ear_Fungus_(Au.png",
    "Lace_Web_Spider_(Ama.png",
    "Large_Red_Damselfly_.png",
    "Marmalade_Hoverfly_(.png",
    "Marsh_Frog_(Pelophyl.png",
    "Migrant_Hawker_drago.png",
    "Natterjack_Toad_(Epi.png",
    "Painted_Lady_butterf.png",
    "Palmate_Newt_(Lissot.png",
    "Panther_Cap_mushroom.png",
    "Peacock_butterfly_(A.png",
    "Raft_Spider_(Dolomed.png",
    "Red_Admiral_butterfl.png",
    "Red-tailed_Bumblebee.png",
    "Running_Crab_Spider_.png",
    "Sand_Lizard_(Lacerta.png",
    "Scarlet_Elf_Cup_fung.png",
    "Seven-spot_Ladybird_.png",
    "Shaggy_Inkcap_mushro.png",
    "Slow_Worm_(Anguis_fr.png",
    "Small_Tortoiseshell_.png",
    "Smooth_Snake_(Corone.png",
    "Southern_Hawker_drag.png",
    "Speckled_Wood_butter.png",
    "Stag_Beetle_(Lucanus.png",
    "Stinkhorn_fungus_(Ph.png",
    "Stripe-legged_Spider.png",
    "Thick-legged_Flower_.png",
    "Tree_Bumblebee_(Bomb.png",
    "Wall_Lizard_(Podarci.png",
    "Alpine_Newt_(Ichthy.png",
    "Edible_Frog_(Peloph.png",
    "Emperor_Dragonfly_(.png",
    "Orange_Peel_Fungus_.png",
    "Balearic_shea.png",
    "barn_owl_(Tyt.png",
    "bearded_tit_(.png",
    "black_guillem.png",
    "black_redstar.png",
    "blackcap_(Syl.png",
    "black-headed_.png",
    "black-throate.png",
    "blue_tit_(Cya.png",
    "brambling_(Fr.png",
    "carrion_crow_.png",
    "chaffinch_(Fr.png",
    "coal_tit_(Per.png",
    "collared_dove.png",
    "common_blackb.png",
    "common_crossb.png",
    "common_kingfi.png",
    "common_linnet.png",
    "common_moorhe.png",
    "common_redsha.png",
    "common_sandpi.png",
    "common_snipe_.png",
    "common_swift_.png",
    "common_wood_p.png",
    "cormorant_(Ph.png",
    "corn_bunting_.png",
    "corncrake_(Cr.png",
    "cuckoo_(Cucul.png",
    "dusky_warbler.png",
    "Eurasian_blac.png",
    "Eurasian_curl.png",
    "Eurasian_magp.png",
    "Eurasian_wren.png",
    "European_gold.png",
    "European_gree.png",
    "European_nigh.png",
    "European_robi.png",
    "European_star.png",
    "European_ston.png",
    "firecrest_(Re.png",
    "goldfinch_(Ca.png",
    "great_crested.png",
    "great_spotted.png",
    "great_tit_(Pa.png",
    "grey_heron_(A.png",
    "hen_harrier_(.png",
    "herring_gull_.png",
    "house_sparrow.png",
    "jackdaw_(Corv.png",
    "kestrel_(Falc.png",
    "little_egret_.png",
    "little_owl_(A.png",
    "little_tern_(.png",
    "long-tailed_t.png",
    "mallard_duck_.png",
    "marsh_harrier.png",
    "meadow_pipit_.png",
    "mute_swan_(Cy.png",
    "northern_lapw.png",
    "northern_whea.png",
    "pallas's_warb.png",
    "peregrine_fal.png",
    "pied_wagtail_.png",
    "pomarine_skua.png",
    "red_kite_(Mil.png",
    "red-backed_sh.png",
    "red-flanked_b.png",
    "red-throated_.png",
    "redwing_(Turd.png",
    "reed_bunting_.png",
    "ring_ouzel_(T.png",
    "rook_(Corvus_.png",
    "roseate_tern_.png",
    "rustic_buntin.png",
    "sand_martin_(.png",
    "serin_(Serinu.png",
    "shag_(Gulosus.png",
    "shore_lark_(E.png",
    "skylark_(Alau.png",
    "snow_bunting_.png",
    "song_thrush_(.png",
    "spotted_flyca.png",
    "tawny_owl_(St.png",
    "tree_pipit_(A.png",
    "water_rail_(R.png",
    "whinchat_(Sax.png",
    "white-tailed_.png",
    "wood_warbler_.png",
    "woodcock_(Sco.png",
    "woodlark_(Lul.png",
    "yellow_wagtai.png",
    "Plantago major.png",
    "Potentilla anserina.png",
    "Epilobium hirsutum.png",
    "Mentha spicata.png",
    "Raphanus raphanistrum.png",
    "Stellaria media.png",
    "Calystegia sepium.png",
    "Veronica chamaedrys.png",
    "Lamium purpureum.png",
    "Pentaglottis sempervirens.png",
    "Polygala vulgaris.png",
    "Prunella vulgaris.png",
    "Stellaria holostea.png",
    "Ranunculus aquatilis.png",
    "Equisetum palustre.png",
    "Cytisus scoparius.png",
    "Pulicaria dysenterica.png",
    "Armeria maritima.png",
    "Caltha palustris.png",
    "Centaurium erythraea.png",
    "Hypochaeris radicata.png",
    "Linaria vulgaris.png",
    "Geranium pratense.png",
    "Lamium galeobdolon.png",
    "Valeriana officinalis.png",
    "Lamium album.png",
    "Iris pseudacorus.png",
    "Dactylorhiza fuchsii.png",
    "Eryngium maritimum.png",
    "Sanguisorba officinalis.png",
    "Lonicera periclymenum.png",
    "Viola palustris.png",
    "Pastinaca sativa.png",
    "Lythrum salicaria.png",
    "Cerastium fontanum.png",
    "Persicaria bistorta.png",
    "Achillea ptarmica.png",
    "Geum urbanum.png",
    "Salvia verbenaca.png",
    "Stachys palustris.png",
    "Filipendula ulmaria.png",
    "Angelica sylvestris.png",
    "Rhinanthus minor.png",
    "Thymus polytrichus.png",
    "Galeopsis tetrahit.png",
    "Euphrasia officinalis.png",
    "Allium vineale.png",
    "Lathyrus pratensis.png",
    "Campanula rotundifolia.png",
    "Centaurea nigra.png",
    "Betonica officinalis.png",
    "Clinopodium vulgare.png",
    "Cornus sanguinea.png",
    "Origanum vulgare.png",
    "Centaurea scabiosa.png",
    "Daucus carota.png",
    "Fragaria vesca.png",
    "Primula vulgaris.png",
    "Mentha aquatica.png",
    "Comarum palustre.png",
    "Geranium robertianum.png",
    "Malva sylvestris.png",
    "Oxalis acetosella.png",
    "Galium verum.png",
    "Ajuga reptans.png",
    "Viola tricolor.png",
    "Anemone nemorosa.png",
    "Centaurea cyanus.png",
    "Silene dioica.png",
    "Heracleum sphondylium.png",
    "Jacobaea vulgaris.png",
    "Viola riviniana.png",
    "Cardamine pratensis.png",
    "Glebionis segetum.png",
    "Lotus corniculatus.png",
    "Prunus spinosa.png",
    "Knautia arvensis.png",
    "Ficaria verna.png",
    "Achillea millefolium.png",
    "Allium ursinum.png",
    "Betula pendula.png",
    "Crataegus monogyna.png",
    "Ranunculus acris.png",
    "Sambucus nigra.png",
    "Papaver rhoeas.png",
    "Digitalis purpurea.png",
    "Bellis perennis.png",
    "Hyacinthoides non-scripta.png",
    "Urtica dioica.png",
    "Quercus robur.png",
    "Taraxacum officinale.png",
    "red squirrel.png",
    "European rabbit.png",
    "red fox.png",
    "European hare.png",
    "European badger.png",
    "roe deer.png",
    "European mole.png",
    "European otter.png",
    "European water vole.png",
    "bat.png",
    "hazel dormouse.png",
    "wood mouse.png",
    "Eurasian beaver.png",
    "brown rat.png",
    "lesser horseshoe bat.png",
    "brown long-eared bat.png",
    "Reeves's muntjac.png",
    "red deer.png",
    "noctule bat.png",
    "pygmy shrew.png",
    "grey seal.png",
    "stoat.png",
    "Natterer's bat.png",
    "harbour porpoise.png",
    "pipistrelle bat genus.png",
    "field vole.png",
    "bank vole.png",
    "common shrew.png",
    "harbour seal.png",
    "mouse-eared bats.png",
    "American mink.png",
    "fallow deer.png",
    "weasel.png",
    "greater horseshoe bat.png",
    "mammals.png",
    "bottlenose dolphin.png",
    "mountain hare.png",
    "pine marten.png",
    "European polecat.png",
    "serotine bat.png",
    "Leisler’s bat.png",
    "yellow-necked mouse.png",
    "voles.png",
    "harvest mouse.png",
    "long-eared bats.png",
    "Eurasian water shrew.png",
    "Chinese water deer.png",
    "house mouse.png",
    "whiskered_Brandt’s bat.png",
    "whiskered bat.png",
    "minke whale.png",
    "common dolphin.png",
    "barbastelle bat.png",
    "shrews.png",
    "sika deer.png",
    "European wildcat.png",
    "deer family.png",
    "seals, sea lions, walruses.png",
    "coypu.png",
    "Nathusius’ pipistrelle.png",
    "domestic goat.png",
    "vesper bats.png",
    "oceanic dolphins.png",
    "Risso’s dolphin.png",
    "wild boar.png",
    "domestic cat.png",
    "elephants.png",
    "noctule_serotine bat group.png",
    "mice and rats.png",
    "Brandt’s bat.png",
    "wild horse.png",
    "squirrels.png",
    "noctule bats.png",
    "shrews.png",
    "lesser white-toothed shrew.png",
    "white-beaked dolphin.png",
    "domestic ferret.png",
    "mice genus.png",
    "Bechstein’s bat.png",
    "wildcat_domestic cat hybrid.png",
    "ferret_polecat hybrid.png",
    "black rat.png",
    "rats, genus.png",
    "Irish hare.png",
    "humpback whale.png",
    "red-necked wallaby.png",
    "greater white-toothed shrew.png",
    "rodents, order.png",
    "common vole.png",
    "whales, dolphins, porpoises, order.png",
    "hares, genus.png",
    "bison, genus.png",
    "moles, family.png",
    "stoat, nominate subspecies.png",
    "Eastern grey squirrel.png",
    "European hedgehog.png",
    "soprano pipistrelle bat.png",
    "common pipistrelle bat.png"
];
